[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "DKL"
version = "0.1.0"
dependencies = [
    "numpy",
    "torch",
]

[tool.hatch.build.targets.wheel]
packages = ["src/DKL"]